plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.google.protobuf' version '0.9.4'
}


group = 'com.gienyne.industrialedgegateway'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


repositories {
    mavenCentral()
    maven { url 'https://repo.eclipse.org/content/repositories/paho-releases/' }
}


dependencies {

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    runtimeOnly 'org.postgresql:postgresql'

    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'

    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'

    implementation 'com.google.protobuf:protobuf-java:3.25.5'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    
}


protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.25.5'
    }
}


tasks.named('test'){
    useJUnitPlatform()
}